notifications:
  email: false

sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose run concha_twitter /bin/sh -c "npm run lint && npm test && npm run coveralls"

#after_success:
#- npm run coveralls

after_script:
  - docker-compose down
