version: "3"

volumes:
  database:
  messagebroker:

services:

  mongo:
    # @todo
    # Container name should match the name given in the mongo connection string
    # Refactor into environment variables, then reinclude the container name.
    # container_name: mongo_concha_twitter
    image: mvertes/alpine-mongo:3.4.9-0
    ports:
      - 27017
    volumes:
      - database:/data/db

  rabbitmq:
    # @todo
    # Container name should match the name given in the mongo connection string
    # Refactor into environment variables, then reinclude the container name.
    # container_name: rabbitmq_concha_twitter
    image: rabbitmq:3.6.12-alpine
    ports:
      - 5672:5672
    volumes:
      - messagebroker:/data/messages

  concha_twitter:
    # @todo
    # Container name should match the name given in the mongo connection string
    # Refactor into environment variables, then reinclude the container name.
    # container_name: concha_twitter
    build: .
    environment:
      - NODE_CONFIG_DIR=/app/src/config
    volumes:
      # Make the following available to docker so that changes made on the host
      # are immediately available inside the docker container.
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./npm-shrinkwrap.json:/app/npm-shrinkwrap.json
    command: npm run debug
    ports:
      # Expose port to host machine for debugging
      - 80:80
    links:
      - mongo
