version: "3"

volumes:
  mongodata:

services:

  mongo:
    # @todo
    # Container name should match the name given in the mongo connection string
    # Refactor into environment variables, then reinclude the container name.
    # container_name: mongo_concha_twitter
    image: mongo:3.0.15-wheezy
    ports:
      - 27017
    volumes:
      - mongodata:/data/db

  concha_twitter:
    # @todo
    # Container name should match the name given in the mongo connection string
    # Refactor into environment variables, then reinclude the container name.
    # container_name: concha_twitter
    build: .
    volumes:
      # Make the following directories available to docker so that changes made on the host
      # are immediately available inside the docker container.
      - ./src:/app/src
      - ./test:/app/test

      # Make package.json available to Docker so that new packages added during the test/develop
      # lifecycle are reflected back to the host, where they can be commited to github.
      - ./package.json:/app/package.json

      # Make npm-shrinkwrap.json available to Docker so that changes made by npm shrinkwrap 
      # in the docker container are reflected back to the host, where they can be committed to
      # github.
      - ./npm-shrinkwrap.json:/app/npm-shrinkwrap.json

      # Make coveralls available to Docker, for local instrumentation
      - ./.coveralls.yml:/app/.coveralls.yml
    command: npm run debug
    ports:
      # Expose port to host machine for debugging
      - 80:80
    links:
      - mongo
